name: Weather Report

on:
  push:
    branches: [main, daily/cicd]
    paths: # 改到匹配目录时才会跑
      - 'apps/weather-report/**'
      - '.github/workflows/weather-report.yml'
  pull_request:
    branches: [main, daily/cicd]
    paths:
      - 'apps/weather-report/**'
      - '.github/workflows/weather-report.yml'
  repository_dispatch:
    types: [cron_trigger] # 这里的类型名称可以自定义
  workflow_dispatch:

jobs:
  weather-report-push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps: &weather-report-steps
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run weather report CI
        uses: ./apps/weather-report/.github/actions

  weather-report-pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps: *weather-report-steps

  weather-report-schedule:
    if: github.event_name == 'repository_dispatch' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Check out test branch
        uses: actions/checkout@v4
        with:
          ref: daily/cicd  # 显式指定拉取测试分支，避免 checkout 到默认的 main 分支
          
      - name: Run weather report CI
        uses: ./apps/weather-report/.github/actions
