name: Weather Report

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  weather-report:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run weather report CI
        uses: ./weather-report/apps/weather-report/.github/actions/ci