name: Weather Report

on:
  push:
    branches: [main, daily/cicd]
    paths: # 改到匹配目录时才会跑
      - 'apps/weather-report/**'
      - '.github/workflows/weather-report.yml'
  pull_request:
    branches: [main, daily/cicd]
    paths:
      - 'apps/weather-report/**'
      - '.github/workflows/weather-report.yml'
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  weather-report-push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run weather report CI
        uses: ./apps/weather-report/.github/actions

  weather-report-pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run weather report CI
        uses: ./apps/weather-report/.github/actions

  weather-report-schedule:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run weather report CI
        uses: ./apps/weather-report/.github/actions
